services:
  - type: web
    name: bursa-karavanli-bahce-cms
    env: python
    rootDir: cms
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: bursa-karavanli-bahce-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
databases:
  - name: bursa-karavanli-bahce-db
    databaseName: bursa_karavanli_bahce
    user: bursa_karavanli_bahce
