# Generated by Django 5.0.14 on 2026-06-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Yeriniz sizi bekliyor', max_length=160)),
                ('intro_text', models.TextField(blank=True)),
                ('reservation_title', models.CharField(blank=True, max_length=160)),
                ('reservation_text', models.TextField(blank=True)),
                ('faq_title', models.CharField(blank=True, max_length=160)),
                ('faq_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Bahçeden anlar', max_length=160)),
                ('intro_text', models.TextField(blank=True)),
                ('cta_title', models.CharField(blank=True, max_length=160)),
                ('cta_text', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
