# Generated by Django 5.0.14 on 2026-06-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_homepage_hero_content_herostat'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(help_text='experience, facilities, nearby, pricing, reviews or faq', max_length=40, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('lead', models.TextField(blank=True)),
                ('aside_title', models.CharField(blank=True, max_length=160)),
                ('aside_text', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
