# Generated by Django 5.0.14 on 2026-06-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_homepagesection_pricingcard_experiencecard'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facilities_badge_subtitle',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facilities_badge_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facilities_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facilities_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
